
name: Run WhatsApp Bot

on:
  push:
    branches:
      - main  # Atur branch sesuai dengan kebutuhan Anda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: node bot.js  # Ganti "bot.js" dengan nama skrip bot WhatsApp Anda
